### ISSUE TITLE
Consider IndexMap + shift_remove instead of LinkedHashMap

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/federation-next#140]
`src/query_plan/operation.rs` contains this comment:

> Note that this must be a `LinkedHashMap` so that removals don't change the order.

Instead of a `remove` method, [`IndexMap`](https://docs.rs/indexmap/latest/indexmap/map/struct.IndexMap.html) has both `swap_remove` and `shift_remove`. Only the former changes the iteration order of some remaining items. The trade-off is that the latter takes O(n) time (like `Vec::remove`). This may still be a win over `LinkedHashMap`, which despite better algorithmic complexity in theory probably has more memory fragmentation. Let’s try it when we can get some performance numbers.

The `linked-hash-map` crate is also “in maintenance mode, due to insufficient maintainer resources”.

**Comment by sachindshinde** [comment]
This was an easy enough change to make, so I ended up doing it in https://github.com/apollographql/federation-next/pull/135/commits/7daa28f06618b0b087b563cedc01ce3d9e247ba1

**Comment by sachindshinde** [comment]
(If we notice that we're spending a lot of time in `shift_remove()`, maybe we can reconsider `linked_hash_map` or some kind of alternative)
