### ISSUE TITLE
[feat] auto generate fragments instead of reusing user provided ones

### ISSUE THREAD

**Issue by dariuszkuc** [apollographql/federation-next#176]
**This ticket has been moved to https://apollographql.atlassian.net/browse/FED-76.**

---

Instead of attempting to reuse user provided fragments which requires complex rebasing logic we should look into an alternative of auto-generating the fragments.

See https://github.com/apollographql/federation/issues/2892 for details.

**Comment by samuelAndalon** [comment]
original PR in federation-js
https://github.com/apollographql/federation/pull/2893/files

this can be even contributed to graphql-js, graphql-java, any spec implementation.
not related to federation at all, it applies to any syntactically valid AST no need for an schema.

**Comment by duckki** [comment]
Related PR for graphql-js: https://github.com/graphql/graphql-js/pull/4025

**Comment by SimonSapin** [comment]
Let’s continue tracking this in https://apollographql.atlassian.net/browse/FED-76 as this repo is being archived.
