### ISSUE TITLE
Rework error handling

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/federation-next#181]
**This ticket has been moved to https://apollographql.atlassian.net/browse/FED-65.**

---

For example:

- Consider merging `FederationSpecError`, `SpecError`, `LinkError` into `FederationError`. (Conversion from the former is unimplemented with `todo!()`)
- `SingleFederationError::Internal` is used in many places. These should be split between things we expect to never happen for any input unless there’s a bug v.s. other cases. The latter could be dedicated enum variants
- `LinkError` should contain a source location
- Include broken value in `Import::from_hir_value` error. `ast::Value` implements `Display` now.
- Dedicated error code/variant for `QueryPlanningTraversal::handle_open_branch`

**Comment by lrlna** [comment]
this is also related to https://github.com/apollographql/federation-planning/issues/510

**Comment by SimonSapin** [comment]
I thought we had something already but didn’t find it in this repo!
