### ISSUE TITLE
Port NormalizedSelectionSet::add_back_typename_in_attachments / add_typename_field_for_abstract_types

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/federation-next#209]
https://github.com/apollographql/federation-next/blob/173b40b9c4ce50319727d8ebd4e9dc200f848aff/src/query_plan/operation.rs#L1360-L1371

**Comment by goto-bus-stop** [comment]
I think these just refer to:
- https://github.com/apollographql/federation-next/issues/147
- https://github.com/apollographql/federation-next/issues/148

**Comment by lrlna** [comment]
yes those are the two issues, i'll close this one
