### ISSUE TITLE
Remove @core supergraph support

### ISSUE THREAD

**Issue by goto-bus-stop** [apollographql/federation-next#225]
**This ticket has been moved to https://apollographql.atlassian.net/browse/FED-86.**

---

`@core` is part of Fed v1, and early Fed v2 betas. We don't intend to support fed v1 in the Rust query planner.

For now we add `@core` for compatibility since many tests across the organisation rely on the `@core` directives from fed v2 betas. It's not intended to support fed v1 long term.

Once that has been upgraded, we intend to remove `@core` directive support in supergraphs from apollo-federation.

**Comment by dariuszkuc** [comment]
Related: https://github.com/apollographql/federation-next/pull/223
