### ISSUE TITLE
epic: operation signature

### ISSUE THREAD

**Issue by jeffjakub** [apollographql/federation-next#26]
**This ticket has been moved to https://apollographql.atlassian.net/browse/FED-93.**

---

As an engineer, I would like to replace common graphql-js functions with native rust functions so I may leave graphql-js by the side of the road. 

Acceptance Criteria
- Articulate a list of Validation, introspection, operation signature jobs to be done. As a later step we can groom this further into issues or sets of issues based on our thoughts on their rough sizing.

**Comment by goto-bus-stop** [comment]
From https://github.com/apollographql/apollo-rs/issues/145:

> Some of the requirements for the moment include:
> - omitting unused values: which removes operations and fragments that aren't going to be used when executing
> - normalising literals: which replaces all numeric and string literals as well as list and object input values with "empty" values
> - removing aliases, which removes field aliasing from the query
> - sorting the AST
