### ISSUE TITLE
[SPLIT] Operation processing (query plan business logic)

### ISSUE THREAD

**Issue by sachindshinde** [apollographql/federation-next#29]
During query planning, we should be able to parse/validate operations into a representation suitable for query planning, and process operations (and their fragments) so that they may be used for query planning.

This is specifically steps 5-7 of [this query-planning summary](https://github.com/apollographql/federation-planning/issues/456), i.e.:
1. Parse and validate the operation against the API schema (similar to schemas, `federation-internals` has a representation of operations that provides capabilities useful for federation-y things, e.g. rebasing).
2. Modify operation and fragments (e.g. adding `__typename` where needed, removing introspection fields, normalizing `@defer` usages).
3. Expand fragments in operations for query-planning purposes, and rebase fragments on subgraphs (to be used in subgraph fetches).

**Comment by abernix** [comment]
@dariuszkuc Is this still on-track to split up or are we re-considering that / is it too late to split it meaningfully? 😄

**Comment by dariuszkuc** [comment]
superseded by https://github.com/apollographql/federation-next/issues/88
