### ISSUE TITLE
Query graph traversal (query plan business logic)

### ISSUE THREAD

**Issue by sachindshinde** [apollographql/federation-next#30]
During query planning, we need to use the operation to traverse the query graph and generate options for each closed branch (leaf field).

This is specifically step 8 of [this query-planning summary](https://github.com/apollographql/federation-planning/issues/456). Note that if it's possible to cleanly punt on porting feature-specific code for later (e.g. subscriptions), we should take the opportunity to do so, in the interests of delivering incrementally.

**Comment by hwillson** [comment]
Something to consider - can @sachindshinde pair with @SimonSapin on this work, to make sure we're cross-pollinating?

**Comment by lrlna** [comment]
closing as duplicate of smaller issues.
