### ISSUE TITLE
epic: testing - performance (router)

### ISSUE THREAD

**Issue by jeffjakub** [apollographql/federation-next#33]
- [ ] performance tests (router) (placeholder @jeff to follow up w/ Polaris team)
- [ ] Using the data set defined in query planner performance epic, establish a comparable end-to-end router performance test that will permit us to exercise federation and federation-next to measure, CPU, memory and schema reload latency.

**Comment by dariuszkuc** [comment]
Initial integration already setup. Further integrations have a separate tracking items.
