### ISSUE TITLE
ensure consistent order of how we print supergraph schemas

### ISSUE THREAD

**Issue by dariuszkuc** [apollographql/federation-next#60]
**This ticket has been moved to https://apollographql.atlassian.net/browse/FED-64.**

---

Printed SDL should match the order of the [JS implementation](https://github.com/apollographql/federation/blob/main/internals-js/src/print.ts#L48). By default, JS prints schema first, followed by directives and closing up with types. Directives and types are printed in alphabetical order (meaning `a` < `A`).

Current RS implementation attempts to do the similar thing

```
    fn print_sdl(schema: &Schema) -> String {
        let mut schema = schema.clone();
        schema.types.sort_keys();
        schema.directive_definitions.sort_keys();
        schema.to_string()
    }
```

Difference is that RS compares characters ASCII values so `A` < `a`. We should try to avoid making any changes to this behavior to ensure that users can seamlessly upgrade from JS to RS implementation without any changes to their supergraph.

**Comment by goto-bus-stop** [comment]
The API schema implementations in JS and Rust retain the input order, so at the moment we don't have anything to do here. When we do composition we'll need to sort, which can be done just by:

```rust
schema.types.sort_by_cached_key(|name, _ty| name.to_ascii_lowercase());
```

**Comment by SimonSapin** [comment]
The Unicode version of transforming a string to make comparison or sort case-independent is called “case folding”. But is it that what JS does or does it have something like Unicode “collation“?

Or, maybe we can decide `to_ascii_lowercase` is Good Enough if we assume that almost all GraphQL names are ASCII in practice.

**Comment by goto-bus-stop** [comment]
JS uses `localeCompare`, so it's Unicode collation, and I think it's at least always en-US.

Names are ASCII by spec.

**Comment by goto-bus-stop** [comment]
Moving this to composition ... though it's more of a "make sure this works" as part of that work than a separate task item

**Comment by goto-bus-stop** [comment]
This is one way we could address it, adding a `Display` impl to `FederationSchema` that sorts during printing: https://github.com/apollographql/federation-next/commit/568e8947b7d81456dfc08c351505072a2eadf9f1
