### ISSUE TITLE
Compute best fetch dependency graph given the options for each branch (query plan business logic)

### ISSUE THREAD

**Issue by sachindshinde** [apollographql/federation-next#77]
This GH issue is the first part of https://github.com/apollographql/federation-next/issues/31 .

Specifically:
- Pruning the options for each branch.
- Generating the initial partial fetch dependency graph and remaining options.
- Iterating through all possible fetch dependency graphs from the initial one, and returning the one with best cost.

More specifically, this issue is for porting `QueryPlanningTraversal.computeBestPlanFromClosedBranches()` and its code dependencies.

**Comment by hwillson** [comment]
Something to consider - can @sachindshinde pair with @SimonSapin on this work, to make sure we're cross-pollinating?

**Comment by abernix** [comment]
@sachindshinde can you drop links to the relevant JS code? thx!

**Comment by lrlna** [comment]
closing as duplicate of smaller issues.
